/* Generated by `num import openapi --client`. Review before production use. */
/* Source module: generated.customer */

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface NumOpenApiRequest {
  operation: string;
  method: string;
  path: string;
  pathParams: Record<string, string | number | boolean>;
  query: Record<string, string | number | boolean | null | undefined>;
  body?: JsonValue;
}

export interface NumOpenApiTransport {
  request<T>(request: NumOpenApiRequest): Promise<T>;
}

export interface CustomerProfile {
  active: boolean;
  email: string;
  id: string;
}

export interface RefundRequest {
  amount: number;
  payment_id: string;
}

export interface RefundResponse {
  approved: boolean;
  id: string;
}

export class CustomerPortalClient {
  constructor(private readonly transport: NumOpenApiTransport) {}

  /** POST /refunds */
  // OpenAPI security requirement for operation `create_refund`: `bearerAuth`; authentication binding is not generated yet
  async create_refund(body: RefundRequest): Promise<RefundResponse> {
    return this.transport.request<RefundResponse>({
      operation: "create_refund",
      method: "POST",
      path: "/refunds",
      pathParams: {},
      query: {},
      body: body as JsonValue,
    });
  }

  /** GET /customers/{customer_id} */
  // OpenAPI security requirement for operation `get_customer`: `bearerAuth`; authentication binding is not generated yet
  // OpenAPI parameter `X-Trace-Id` is preserved in the stub signature; review transport serialization before production use.
  async get_customer(customer_id: string, include_inactive: boolean, xTraceId: string): Promise<CustomerProfile> {
    return this.transport.request<CustomerProfile>({
      operation: "get_customer",
      method: "GET",
      path: "/customers/{customer_id}",
      pathParams: { "customer_id": customer_id },
      query: { "include_inactive": include_inactive },
    });
  }

}
