use num_compiler::{
    ast::{
        CallableDecl, ConnectorDecl, Declaration, EnumDecl, Module, Param, TypeBody, TypeDecl,
        TypeRef,
    },
    builtins::{self, BuiltinKind},
};
use serde_json::{json, Value};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConnectorSdkLanguage {
    TypeScript,
    Python,
    Java,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConnectorSdk {
    pub language: ConnectorSdkLanguage,
    pub connector_count: usize,
    pub method_count: usize,
    pub type_count: usize,
    pub contents: String,
}

impl ConnectorSdk {
    pub fn to_json(&self) -> Value {
        json!({
            "language": match self.language {
                ConnectorSdkLanguage::TypeScript => "typescript",
                ConnectorSdkLanguage::Python => "python",
                ConnectorSdkLanguage::Java => "java",
            },
            "connector_count": self.connector_count,
            "method_count": self.method_count,
            "type_count": self.type_count,
        })
    }
}

pub fn render_typescript_sdk(module: &Module) -> ConnectorSdk {
    let type_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Type(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let enum_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Enum(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let connectors = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Connector(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();

    let mut wrappers = WrapperUsage::default();
    for decl in &type_decls {
        collect_type_wrappers(decl, &mut wrappers);
    }
    for decl in &enum_decls {
        collect_enum_wrappers(decl, &mut wrappers);
    }
    for connector in &connectors {
        collect_connector_wrappers(connector, &mut wrappers);
    }

    let mut out = String::new();
    out.push_str("/* Generated by num connector-sdk. Do not edit by hand. */\n\n");
    render_egress_context_types(&mut out);
    render_runtime_wrappers(&mut out, &wrappers);
    render_type_declarations(&mut out, &type_decls);
    render_enum_declarations(&mut out, &enum_decls);
    render_connector_interface(&mut out, &connectors);

    ConnectorSdk {
        language: ConnectorSdkLanguage::TypeScript,
        connector_count: connectors.len(),
        method_count: connectors
            .iter()
            .map(|connector| connector.methods.len())
            .sum(),
        type_count: type_decls.len() + enum_decls.len(),
        contents: out,
    }
}

pub fn render_python_sdk(module: &Module) -> ConnectorSdk {
    let type_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Type(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let enum_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Enum(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let connectors = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Connector(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();

    let mut wrappers = WrapperUsage::default();
    for decl in &type_decls {
        collect_type_wrappers(decl, &mut wrappers);
    }
    for decl in &enum_decls {
        collect_enum_wrappers(decl, &mut wrappers);
    }
    for connector in &connectors {
        collect_connector_wrappers(connector, &mut wrappers);
    }

    let mut out = String::new();
    out.push_str("# Generated by num connector-sdk. Do not edit by hand.\n");
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from typing import Any, Generic, Literal, Protocol, TypeAlias, TypeVar\n\n");
    render_python_typevars(&mut out, &type_decls, &wrappers);
    render_python_egress_context_types(&mut out);
    render_python_runtime_wrappers(&mut out, &wrappers);
    render_python_type_declarations(&mut out, &type_decls);
    render_python_enum_declarations(&mut out, &enum_decls);
    render_python_connector_protocols(&mut out, &connectors);

    ConnectorSdk {
        language: ConnectorSdkLanguage::Python,
        connector_count: connectors.len(),
        method_count: connectors
            .iter()
            .map(|connector| connector.methods.len())
            .sum(),
        type_count: type_decls.len() + enum_decls.len(),
        contents: out,
    }
}

pub fn render_java_sdk(module: &Module) -> ConnectorSdk {
    let type_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Type(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let enum_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Enum(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let functions = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Function(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let connectors = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Connector(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();

    let mut wrappers = WrapperUsage::default();
    for decl in &type_decls {
        collect_type_wrappers(decl, &mut wrappers);
    }
    for decl in &enum_decls {
        collect_enum_wrappers(decl, &mut wrappers);
    }
    for function in &functions {
        collect_callable_wrappers(function, &mut wrappers);
    }
    for connector in &connectors {
        collect_connector_wrappers(connector, &mut wrappers);
    }

    let mut out = String::new();
    out.push_str("/* Generated by num connector-sdk. Do not edit by hand. */\n\n");
    out.push_str("import java.util.List;\n");
    out.push_str("import java.util.Map;\n");
    out.push_str("import java.util.Optional;\n\n");
    out.push_str("public final class NumConnectorSdk {\n");
    out.push_str("  private NumConnectorSdk() {}\n\n");
    render_java_context_types(&mut out);
    render_java_runtime_wrappers(&mut out, &wrappers);
    render_java_type_declarations(&mut out, &type_decls);
    render_java_enum_declarations(&mut out, &enum_decls);
    render_java_function_interface(&mut out, &functions);
    render_java_connector_interfaces(&mut out, &connectors);
    out.push_str("}\n");

    ConnectorSdk {
        language: ConnectorSdkLanguage::Java,
        connector_count: connectors.len(),
        method_count: connectors
            .iter()
            .map(|connector| connector.methods.len())
            .sum::<usize>()
            + functions.len(),
        type_count: type_decls.len() + enum_decls.len(),
        contents: out,
    }
}

fn render_egress_context_types(out: &mut String) {
    out.push_str("export interface NumConnectorArgLabel {\n");
    out.push_str("  index: number;\n");
    out.push_str("  name: string;\n");
    out.push_str("  type: string;\n");
    out.push_str("  source?: string | null;\n");
    out.push_str("  privacy?: \"public\" | \"internal\" | \"private\" | \"sensitive\" | \"secret\" | \"regulated\" | string | null;\n");
    out.push_str("  trust?: \"untrusted\" | \"trusted\" | \"verified\" | string | null;\n");
    out.push_str("}\n\n");
    out.push_str("export interface NumConnectorEgressContext {\n");
    out.push_str("  connector: string;\n");
    out.push_str("  method_name: string;\n");
    out.push_str("  method: string;\n");
    out.push_str("  capability: string;\n");
    out.push_str("  actor: string;\n");
    out.push_str("  tenant: string;\n");
    out.push_str("  correlation_id: string;\n");
    out.push_str("  request_id: string;\n");
    out.push_str("  policy_decision: string;\n");
    out.push_str("  arg_labels: NumConnectorArgLabel[];\n");
    out.push_str("}\n\n");
}

#[derive(Debug, Default)]
struct WrapperUsage {
    money: bool,
    option: bool,
    result: bool,
    uncertain: bool,
    secret: bool,
    json: bool,
    document: bool,
    pdf: bool,
    docx: bool,
    spreadsheet_sheet: bool,
    spreadsheet: bool,
    image: bool,
    ocr_result: bool,
}

fn render_runtime_wrappers(out: &mut String, wrappers: &WrapperUsage) {
    if wrappers.json {
        out.push_str("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n");
    }
    if wrappers.money {
        out.push_str("export interface Money<C extends string = string> {\n");
        out.push_str("  currency: C;\n");
        out.push_str("  cents: number;\n");
        out.push_str("}\n\n");
    }
    if wrappers.option {
        out.push_str("export type Option<T> = T | null;\n\n");
    }
    if wrappers.result {
        out.push_str(
            "export type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };\n\n",
        );
    }
    if wrappers.uncertain {
        out.push_str("export interface Uncertain<T> {\n");
        out.push_str("  value: T;\n");
        out.push_str("  confidence: number;\n");
        out.push_str("  source?: string;\n");
        out.push_str("  explanation?: string;\n");
        out.push_str("  evidence?: string[];\n");
        out.push_str("}\n\n");
    }
    if wrappers.secret {
        out.push_str("export interface Secret<T = string> {\n");
        out.push_str("  name: string;\n");
        out.push_str("  value?: T;\n");
        out.push_str("}\n\n");
    }
    if wrappers.document {
        out.push_str("export interface Document {\n");
        out.push_str("  id: string;\n");
        out.push_str("  name: string;\n");
        out.push_str("  mime_type: string;\n");
        out.push_str("  size_bytes: number;\n");
        out.push_str("  source: string;\n");
        out.push_str("  privacy: string;\n");
        out.push_str("  trust: string;\n");
        out.push_str("}\n\n");
    }
    if wrappers.pdf {
        out.push_str("export interface Pdf extends Document {\n");
        out.push_str("  document: Document;\n");
        out.push_str("  page_count: number;\n");
        out.push_str("}\n\n");
    }
    if wrappers.docx {
        out.push_str("export interface Docx extends Document {\n");
        out.push_str("  document: Document;\n");
        out.push_str("  title: string;\n");
        out.push_str("  creator: string;\n");
        out.push_str("  paragraph_count: number;\n");
        out.push_str("}\n\n");
    }
    if wrappers.spreadsheet_sheet {
        out.push_str("export interface SpreadsheetSheet {\n");
        out.push_str("  name: string;\n");
        out.push_str("  row_count: number;\n");
        out.push_str("  column_count: number;\n");
        out.push_str("  header_row: number;\n");
        out.push_str("}\n\n");
    }
    if wrappers.spreadsheet {
        out.push_str("export interface Spreadsheet extends Document {\n");
        out.push_str("  document: Document;\n");
        out.push_str("  sheet_count: number;\n");
        out.push_str("  sheets: SpreadsheetSheet[];\n");
        out.push_str("  sheet_names: string[];\n");
        out.push_str("}\n\n");
    }
    if wrappers.image {
        out.push_str("export interface Image extends Document {\n");
        out.push_str("  document: Document;\n");
        out.push_str("  width: number;\n");
        out.push_str("  height: number;\n");
        out.push_str("  format: string;\n");
        out.push_str("}\n\n");
    }
    if wrappers.ocr_result {
        out.push_str("export interface OcrResult {\n");
        out.push_str("  image: Image;\n");
        out.push_str("  text: string;\n");
        out.push_str("  confidence: number;\n");
        out.push_str("  provider: string;\n");
        out.push_str("  model: string;\n");
        out.push_str("  source: string;\n");
        out.push_str("  privacy: string;\n");
        out.push_str("  trust: string;\n");
        out.push_str("}\n\n");
    }
}

fn render_type_declarations(out: &mut String, declarations: &[&TypeDecl]) {
    for decl in declarations {
        match &decl.body {
            TypeBody::Struct(fields) => {
                out.push_str("export interface ");
                out.push_str(&decl.name);
                render_generic_params(out, &decl.generic_params);
                out.push_str(" {\n");
                for field in fields {
                    out.push_str("  ");
                    out.push_str(&ts_property_name(&field.name));
                    out.push_str(": ");
                    out.push_str(&type_ref_to_typescript(&field.ty));
                    out.push_str(";\n");
                }
                out.push_str("}\n\n");
            }
            TypeBody::Alias(alias) => {
                out.push_str("export type ");
                out.push_str(&decl.name);
                render_generic_params(out, &decl.generic_params);
                out.push_str(" = ");
                out.push_str(&type_ref_to_typescript(alias));
                out.push_str(";\n\n");
            }
        }
    }
}

fn render_enum_declarations(out: &mut String, declarations: &[&EnumDecl]) {
    for decl in declarations {
        let has_payload = decl
            .variants
            .iter()
            .any(|variant| variant.payload.is_some());
        out.push_str("export type ");
        out.push_str(&decl.name);
        out.push_str(" = ");
        if has_payload {
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str("\n  | ");
                }
                out.push_str("{ kind: \"");
                out.push_str(&variant.name);
                out.push('"');
                if let Some(payload) = &variant.payload {
                    out.push_str("; value: ");
                    out.push_str(&type_ref_to_typescript(payload));
                }
                out.push_str(" }");
            }
            out.push_str(";\n\n");
        } else {
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                out.push('"');
                out.push_str(&variant.name);
                out.push('"');
            }
            out.push_str(";\n\n");
        }
    }
}

fn render_connector_interface(out: &mut String, connectors: &[&ConnectorDecl]) {
    out.push_str("export interface NumConnectors {\n");
    for connector in connectors {
        out.push_str("  ");
        out.push_str(&ts_property_name(&connector.name));
        out.push_str(": {\n");
        for method in &connector.methods {
            out.push_str("    ");
            out.push_str(&ts_property_name(&method.name));
            out.push('(');
            for (index, param) in method.params.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                out.push_str(&ts_property_name(&param.name));
                out.push_str(": ");
                out.push_str(&type_ref_to_typescript(&param.ty));
            }
            if !method.params.is_empty() {
                out.push_str(", ");
            }
            out.push_str("context?: NumConnectorEgressContext");
            out.push_str("): Promise<");
            out.push_str(
                &method
                    .result
                    .as_ref()
                    .map(type_ref_to_typescript)
                    .unwrap_or_else(|| "void".to_string()),
            );
            out.push_str(">;\n");
        }
        out.push_str("  };\n");
    }
    out.push_str("}\n");
}

fn render_python_typevars(out: &mut String, declarations: &[&TypeDecl], wrappers: &WrapperUsage) {
    let mut params = declarations
        .iter()
        .flat_map(|decl| decl.generic_params.iter())
        .map(String::as_str)
        .collect::<Vec<_>>();
    if wrappers.money || wrappers.result || wrappers.uncertain || wrappers.secret {
        params.push("T");
    }
    params.sort();
    params.dedup();
    for param in params {
        out.push_str(&format!("{param} = TypeVar(\"{param}\")\n"));
    }
    if wrappers.money
        || wrappers.result
        || wrappers.uncertain
        || wrappers.secret
        || wrappers.document
        || wrappers.pdf
        || wrappers.docx
        || declarations
            .iter()
            .any(|decl| !decl.generic_params.is_empty())
    {
        out.push('\n');
    }
}

fn render_python_egress_context_types(out: &mut String) {
    out.push_str("JsonValue: TypeAlias = type(None) | bool | int | float | str | list[\"JsonValue\"] | dict[str, \"JsonValue\"]\n\n");
    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class NumConnectorArgLabel:\n");
    out.push_str("    index: int\n");
    out.push_str("    name: str\n");
    out.push_str("    type: str\n");
    out.push_str("    source: str | None = None\n");
    out.push_str("    privacy: str | None = None\n");
    out.push_str("    trust: str | None = None\n\n");
    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class NumConnectorEgressContext:\n");
    out.push_str("    connector: str\n");
    out.push_str("    method_name: str\n");
    out.push_str("    method: str\n");
    out.push_str("    capability: str\n");
    out.push_str("    actor: str\n");
    out.push_str("    tenant: str\n");
    out.push_str("    correlation_id: str\n");
    out.push_str("    request_id: str\n");
    out.push_str("    policy_decision: str\n");
    out.push_str("    arg_labels: list[NumConnectorArgLabel]\n\n");
    out.push_str("def num_connector_egress_context_from_json(value: dict[str, Any] | None) -> NumConnectorEgressContext | None:\n");
    out.push_str("    if not value:\n");
    out.push_str("        return None\n");
    out.push_str("    labels = [\n");
    out.push_str("        NumConnectorArgLabel(\n");
    out.push_str("            index=int(label.get(\"index\", 0)),\n");
    out.push_str("            name=str(label.get(\"name\", \"\")),\n");
    out.push_str("            type=str(label.get(\"type\", \"\")),\n");
    out.push_str("            source=label.get(\"source\") if isinstance(label.get(\"source\"), str) else None,\n");
    out.push_str("            privacy=label.get(\"privacy\") if isinstance(label.get(\"privacy\"), str) else None,\n");
    out.push_str("            trust=label.get(\"trust\") if isinstance(label.get(\"trust\"), str) else None,\n");
    out.push_str("        )\n");
    out.push_str("        for label in value.get(\"arg_labels\", [])\n");
    out.push_str("        if isinstance(label, dict)\n");
    out.push_str("    ]\n");
    out.push_str("    return NumConnectorEgressContext(\n");
    out.push_str("        connector=str(value.get(\"connector\", \"\")),\n");
    out.push_str("        method_name=str(value.get(\"method_name\", \"\")),\n");
    out.push_str("        method=str(value.get(\"method\", \"\")),\n");
    out.push_str("        capability=str(value.get(\"capability\", \"\")),\n");
    out.push_str("        actor=str(value.get(\"actor\", \"\")),\n");
    out.push_str("        tenant=str(value.get(\"tenant\", \"\")),\n");
    out.push_str("        correlation_id=str(value.get(\"correlation_id\", \"\")),\n");
    out.push_str("        request_id=str(value.get(\"request_id\", \"\")),\n");
    out.push_str("        policy_decision=str(value.get(\"policy_decision\", \"\")),\n");
    out.push_str("        arg_labels=labels,\n");
    out.push_str("    )\n\n");
}

fn render_python_runtime_wrappers(out: &mut String, wrappers: &WrapperUsage) {
    if wrappers.money {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Money(Generic[T]):\n");
        out.push_str("    currency: str\n");
        out.push_str("    minor_units: int\n\n");
    }
    if wrappers.result {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Ok(Generic[T]):\n");
        out.push_str("    value: T\n\n");
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Err(Generic[T]):\n");
        out.push_str("    error: T\n\n");
        out.push_str("Result: TypeAlias = Ok[T] | Err[Any]\n\n");
    }
    if wrappers.uncertain {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Uncertain(Generic[T]):\n");
        out.push_str("    value: T\n");
        out.push_str("    confidence: float\n");
        out.push_str("    source: str | None = None\n");
        out.push_str("    explanation: str | None = None\n");
        out.push_str("    evidence: list[str] | None = None\n\n");
    }
    if wrappers.secret {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Secret(Generic[T]):\n");
        out.push_str("    name: str\n");
        out.push_str("    value: T | None = None\n\n");
    }
    if wrappers.document {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Document:\n");
        out.push_str("    id: str\n");
        out.push_str("    name: str\n");
        out.push_str("    mime_type: str\n");
        out.push_str("    size_bytes: int\n");
        out.push_str("    source: str\n");
        out.push_str("    privacy: str\n");
        out.push_str("    trust: str\n\n");
    }
    if wrappers.pdf {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Pdf(Document):\n");
        out.push_str("    document: Document\n");
        out.push_str("    page_count: int\n\n");
    }
    if wrappers.docx {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Docx(Document):\n");
        out.push_str("    document: Document\n");
        out.push_str("    title: str\n");
        out.push_str("    creator: str\n");
        out.push_str("    paragraph_count: int\n\n");
    }
    if wrappers.spreadsheet_sheet {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class SpreadsheetSheet:\n");
        out.push_str("    name: str\n");
        out.push_str("    row_count: int\n");
        out.push_str("    column_count: int\n");
        out.push_str("    header_row: int\n\n");
    }
    if wrappers.spreadsheet {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Spreadsheet(Document):\n");
        out.push_str("    document: Document\n");
        out.push_str("    sheet_count: int\n");
        out.push_str("    sheets: list[SpreadsheetSheet]\n");
        out.push_str("    sheet_names: list[str]\n\n");
    }
    if wrappers.image {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class Image(Document):\n");
        out.push_str("    document: Document\n");
        out.push_str("    width: int\n");
        out.push_str("    height: int\n");
        out.push_str("    format: str\n\n");
    }
    if wrappers.ocr_result {
        out.push_str("@dataclass(frozen=True)\n");
        out.push_str("class OcrResult:\n");
        out.push_str("    image: Image\n");
        out.push_str("    text: str\n");
        out.push_str("    confidence: float\n");
        out.push_str("    provider: str\n");
        out.push_str("    model: str\n");
        out.push_str("    source: str\n");
        out.push_str("    privacy: str\n");
        out.push_str("    trust: str\n\n");
    }
}

fn render_python_type_declarations(out: &mut String, declarations: &[&TypeDecl]) {
    for decl in declarations {
        match &decl.body {
            TypeBody::Struct(fields) => {
                out.push_str("@dataclass(frozen=True)\n");
                out.push_str("class ");
                out.push_str(&decl.name);
                render_python_generic_base(out, &decl.generic_params);
                out.push_str(":\n");
                if fields.is_empty() {
                    out.push_str("    pass\n");
                } else {
                    for field in fields {
                        out.push_str("    ");
                        out.push_str(&python_identifier(&field.name));
                        out.push_str(": ");
                        out.push_str(&type_ref_to_python(&field.ty));
                        out.push('\n');
                    }
                }
                out.push('\n');
            }
            TypeBody::Alias(alias) => {
                out.push_str(&decl.name);
                out.push_str(": TypeAlias = ");
                out.push_str(&type_ref_to_python(alias));
                out.push_str("\n\n");
            }
        }
    }
}

fn render_python_enum_declarations(out: &mut String, declarations: &[&EnumDecl]) {
    for decl in declarations {
        let has_payload = decl
            .variants
            .iter()
            .any(|variant| variant.payload.is_some());
        if has_payload {
            for variant in &decl.variants {
                out.push_str("@dataclass(frozen=True)\n");
                out.push_str("class ");
                out.push_str(&decl.name);
                out.push_str(&variant.name);
                out.push_str(":\n");
                out.push_str("    kind: Literal[\"");
                out.push_str(&escape_python_string(&variant.name));
                out.push_str("\"] = \"");
                out.push_str(&escape_python_string(&variant.name));
                out.push_str("\"\n");
                if let Some(payload) = &variant.payload {
                    out.push_str("    value: ");
                    out.push_str(&type_ref_to_python(payload));
                    out.push('\n');
                }
                out.push('\n');
            }
            out.push_str(&decl.name);
            out.push_str(": TypeAlias = ");
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                out.push_str(&decl.name);
                out.push_str(&variant.name);
            }
            out.push_str("\n\n");
        } else {
            out.push_str(&decl.name);
            out.push_str(": TypeAlias = ");
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                out.push_str("Literal[\"");
                out.push_str(&escape_python_string(&variant.name));
                out.push_str("\"]");
            }
            if decl.variants.is_empty() {
                out.push_str("str");
            }
            out.push_str("\n\n");
        }
    }
}

fn render_python_connector_protocols(out: &mut String, connectors: &[&ConnectorDecl]) {
    for connector in connectors {
        out.push_str("class ");
        out.push_str(&python_connector_protocol_name(&connector.name));
        out.push_str("(Protocol):\n");
        if connector.methods.is_empty() {
            out.push_str("    pass\n\n");
            continue;
        }
        for method in &connector.methods {
            out.push_str("    def ");
            out.push_str(&python_identifier(&method.name));
            out.push_str("(self");
            for param in &method.params {
                out.push_str(", ");
                out.push_str(&python_identifier(&param.name));
                out.push_str(": ");
                out.push_str(&type_ref_to_python(&param.ty));
            }
            out.push_str(", context: NumConnectorEgressContext | None = None) -> ");
            out.push_str(
                &method
                    .result
                    .as_ref()
                    .map(type_ref_to_python)
                    .unwrap_or_else(|| "None".to_string()),
            );
            out.push_str(": ...\n");
        }
        out.push('\n');
    }

    out.push_str("class NumConnectors(Protocol):\n");
    if connectors.is_empty() {
        out.push_str("    pass\n");
        return;
    }
    for connector in connectors {
        out.push_str("    ");
        out.push_str(&python_identifier(&connector.name));
        out.push_str(": ");
        out.push_str(&python_connector_protocol_name(&connector.name));
        out.push('\n');
    }
}

fn render_java_context_types(out: &mut String) {
    out.push_str("  public record NumConnectorArgLabel(\n");
    out.push_str("      int index,\n");
    out.push_str("      String name,\n");
    out.push_str("      String type,\n");
    out.push_str("      String source,\n");
    out.push_str("      String privacy,\n");
    out.push_str("      String trust) {}\n\n");
    out.push_str("  public record NumConnectorContext(\n");
    out.push_str("      String connector,\n");
    out.push_str("      String methodName,\n");
    out.push_str("      String method,\n");
    out.push_str("      String capability,\n");
    out.push_str("      String actor,\n");
    out.push_str("      String tenant,\n");
    out.push_str("      String correlationId,\n");
    out.push_str("      String requestId,\n");
    out.push_str("      String policyDecision,\n");
    out.push_str("      List<NumConnectorArgLabel> argLabels) {}\n\n");
    out.push_str("  public static class NumConnectorException extends Exception {\n");
    out.push_str("    private final String code;\n");
    out.push_str("    private final boolean retryable;\n\n");
    out.push_str(
        "    public NumConnectorException(String code, String message, boolean retryable) {\n",
    );
    out.push_str("      super(message);\n");
    out.push_str("      this.code = code;\n");
    out.push_str("      this.retryable = retryable;\n");
    out.push_str("    }\n\n");
    out.push_str("    public String code() { return code; }\n");
    out.push_str("    public boolean retryable() { return retryable; }\n");
    out.push_str("  }\n\n");
}

fn render_java_runtime_wrappers(out: &mut String, wrappers: &WrapperUsage) {
    if wrappers.json {
        out.push_str(
            "  /** Json maps to boxed primitives, List<Object>, or Map<String, Object>. */\n",
        );
        out.push_str("  public interface JsonValue {}\n\n");
    }
    if wrappers.money {
        out.push_str("  public record Money(String currency, long minorUnits) {}\n\n");
    }
    if wrappers.result {
        out.push_str("  public sealed interface Result<T, E> permits Result.Ok, Result.Err {\n");
        out.push_str("    record Ok<T, E>(T value) implements Result<T, E> {}\n");
        out.push_str("    record Err<T, E>(E error) implements Result<T, E> {}\n");
        out.push_str("  }\n\n");
    }
    if wrappers.uncertain {
        out.push_str("  public record Uncertain<T>(\n");
        out.push_str("      T value,\n");
        out.push_str("      double confidence,\n");
        out.push_str("      String source,\n");
        out.push_str("      String explanation,\n");
        out.push_str("      List<String> evidence) {}\n\n");
    }
    if wrappers.secret {
        out.push_str("  public record Secret<T>(String name, Optional<T> value) {}\n\n");
    }
    if wrappers.document {
        out.push_str("  public record Document(\n");
        out.push_str("      String id,\n");
        out.push_str("      String name,\n");
        out.push_str("      String mimeType,\n");
        out.push_str("      long sizeBytes,\n");
        out.push_str("      String source,\n");
        out.push_str("      String privacy,\n");
        out.push_str("      String trust) {}\n\n");
    }
    if wrappers.pdf {
        out.push_str("  public record Pdf(Document document, long pageCount) {}\n\n");
    }
    if wrappers.docx {
        out.push_str("  public record Docx(Document document, String title, String creator, long paragraphCount) {}\n\n");
    }
    if wrappers.spreadsheet_sheet {
        out.push_str("  public record SpreadsheetSheet(String name, long rowCount, long columnCount, long headerRow) {}\n\n");
    }
    if wrappers.spreadsheet {
        out.push_str("  public record Spreadsheet(Document document, long sheetCount, List<String> sheetNames, List<SpreadsheetSheet> sheets) {}\n\n");
    }
    if wrappers.image {
        out.push_str("  public record Image(Document document, long width, long height, String format) {}\n\n");
    }
    if wrappers.ocr_result {
        out.push_str("  public record OcrResult(\n");
        out.push_str("      Image image,\n");
        out.push_str("      String text,\n");
        out.push_str("      double confidence,\n");
        out.push_str("      String provider,\n");
        out.push_str("      String model,\n");
        out.push_str("      String source,\n");
        out.push_str("      String privacy,\n");
        out.push_str("      String trust) {}\n\n");
    }
}

fn render_java_type_declarations(out: &mut String, declarations: &[&TypeDecl]) {
    for decl in declarations {
        match &decl.body {
            TypeBody::Struct(fields) => {
                out.push_str("  public record ");
                out.push_str(&java_type_name(&decl.name));
                render_java_generic_params(out, &decl.generic_params);
                out.push('(');
                for (index, field) in fields.iter().enumerate() {
                    if index > 0 {
                        out.push_str(", ");
                    }
                    out.push_str(&type_ref_to_java(&field.ty));
                    out.push(' ');
                    out.push_str(&java_identifier(&field.name));
                }
                out.push_str(") {}\n\n");
            }
            TypeBody::Alias(alias) => {
                out.push_str("  public record ");
                out.push_str(&java_type_name(&decl.name));
                render_java_generic_params(out, &decl.generic_params);
                out.push('(');
                out.push_str(&type_ref_to_java(alias));
                out.push_str(" value) {}\n\n");
            }
        }
    }
}

fn render_java_enum_declarations(out: &mut String, declarations: &[&EnumDecl]) {
    for decl in declarations {
        let has_payload = decl
            .variants
            .iter()
            .any(|variant| variant.payload.is_some());
        if has_payload {
            out.push_str("  public sealed interface ");
            out.push_str(&java_type_name(&decl.name));
            out.push_str(" permits ");
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                out.push_str(&java_type_name(&decl.name));
                out.push('.');
                out.push_str(&java_type_name(&variant.name));
            }
            out.push_str(" {\n");
            for variant in &decl.variants {
                out.push_str("    record ");
                out.push_str(&java_type_name(&variant.name));
                out.push('(');
                if let Some(payload) = &variant.payload {
                    out.push_str(&type_ref_to_java(payload));
                    out.push_str(" value");
                }
                out.push_str(") implements ");
                out.push_str(&java_type_name(&decl.name));
                out.push_str(" {}\n");
            }
            out.push_str("  }\n\n");
        } else {
            out.push_str("  public enum ");
            out.push_str(&java_type_name(&decl.name));
            out.push_str(" { ");
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                out.push_str(&java_enum_constant(&variant.name));
            }
            out.push_str(" }\n\n");
        }
    }
}

fn render_java_function_interface(out: &mut String, functions: &[&CallableDecl]) {
    out.push_str("  public interface NumFunctions {\n");
    for function in functions {
        render_java_method_signature(out, &function.name, &function.params, &function.result, 4);
    }
    out.push_str("  }\n\n");
}

fn render_java_connector_interfaces(out: &mut String, connectors: &[&ConnectorDecl]) {
    for connector in connectors {
        out.push_str("  public interface ");
        out.push_str(&java_connector_interface_name(&connector.name));
        out.push_str(" {\n");
        for method in &connector.methods {
            render_java_method_signature(out, &method.name, &method.params, &method.result, 4);
        }
        out.push_str("  }\n\n");
    }

    out.push_str("  public interface NumConnectors {\n");
    for connector in connectors {
        out.push_str("    ");
        out.push_str(&java_connector_interface_name(&connector.name));
        out.push(' ');
        out.push_str(&java_identifier(&connector.name));
        out.push_str("();\n");
    }
    out.push_str("  }\n");
}

fn render_java_method_signature(
    out: &mut String,
    name: &str,
    params: &[Param],
    result: &Option<TypeRef>,
    indent: usize,
) {
    out.push_str(&" ".repeat(indent));
    out.push_str(
        &result
            .as_ref()
            .map(type_ref_to_java)
            .unwrap_or_else(|| "void".to_string()),
    );
    out.push(' ');
    out.push_str(&java_identifier(name));
    out.push('(');
    for (index, param) in params.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        out.push_str(&type_ref_to_java(&param.ty));
        out.push(' ');
        out.push_str(&java_identifier(&param.name));
    }
    if !params.is_empty() {
        out.push_str(", ");
    }
    out.push_str("NumConnectorContext context) throws NumConnectorException;\n");
}

fn render_python_generic_base(out: &mut String, params: &[String]) {
    if params.is_empty() {
        return;
    }
    out.push_str("(Generic[");
    out.push_str(&params.join(", "));
    out.push_str("])");
}

fn render_generic_params(out: &mut String, params: &[String]) {
    if params.is_empty() {
        return;
    }
    out.push('<');
    out.push_str(&params.join(", "));
    out.push('>');
}

fn collect_type_wrappers(decl: &TypeDecl, wrappers: &mut WrapperUsage) {
    match &decl.body {
        TypeBody::Struct(fields) => {
            for field in fields {
                collect_wrappers_from_type(&field.ty, wrappers);
            }
        }
        TypeBody::Alias(alias) => collect_wrappers_from_type(alias, wrappers),
    }
}

fn collect_enum_wrappers(decl: &EnumDecl, wrappers: &mut WrapperUsage) {
    for variant in &decl.variants {
        if let Some(payload) = &variant.payload {
            collect_wrappers_from_type(payload, wrappers);
        }
    }
}

fn collect_connector_wrappers(connector: &ConnectorDecl, wrappers: &mut WrapperUsage) {
    for method in &connector.methods {
        for param in &method.params {
            collect_wrappers_from_type(&param.ty, wrappers);
        }
        if let Some(result) = &method.result {
            collect_wrappers_from_type(result, wrappers);
        }
    }
}

fn collect_callable_wrappers(callable: &CallableDecl, wrappers: &mut WrapperUsage) {
    for param in &callable.params {
        collect_wrappers_from_type(&param.ty, wrappers);
    }
    if let Some(result) = &callable.result {
        collect_wrappers_from_type(result, wrappers);
    }
}

fn collect_wrappers_from_type(ty: &TypeRef, wrappers: &mut WrapperUsage) {
    match parse_type_expr(&ty.raw) {
        TypeExpr::Named { name, args } => {
            match name.as_str() {
                "Money" => wrappers.money = true,
                "Option" => wrappers.option = true,
                "Result" => wrappers.result = true,
                "Uncertain" => wrappers.uncertain = true,
                "Secret" => wrappers.secret = true,
                "Json" => wrappers.json = true,
                "Document" => wrappers.document = true,
                "Pdf" => {
                    wrappers.document = true;
                    wrappers.pdf = true;
                }
                "Docx" => {
                    wrappers.document = true;
                    wrappers.docx = true;
                }
                "SpreadsheetSheet" => {
                    wrappers.spreadsheet_sheet = true;
                }
                "Spreadsheet" => {
                    wrappers.document = true;
                    wrappers.spreadsheet_sheet = true;
                    wrappers.spreadsheet = true;
                }
                "Image" => {
                    wrappers.document = true;
                    wrappers.image = true;
                }
                "OcrResult" => {
                    wrappers.document = true;
                    wrappers.image = true;
                    wrappers.ocr_result = true;
                }
                _ => {}
            }
            for arg in args {
                collect_wrappers_from_type(&TypeRef { raw: arg.render() }, wrappers);
            }
        }
        TypeExpr::StringLiteral(_) => {}
    }
}

fn type_ref_to_typescript(ty: &TypeRef) -> String {
    type_expr_to_typescript(&parse_type_expr(&ty.raw))
}

fn type_ref_to_python(ty: &TypeRef) -> String {
    type_expr_to_python(&parse_type_expr(&ty.raw))
}

fn type_ref_to_java(ty: &TypeRef) -> String {
    type_expr_to_java(&parse_type_expr(&ty.raw))
}

fn type_expr_to_typescript(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::StringLiteral(value) => format!("\"{}\"", escape_ts_string(value)),
        TypeExpr::Named { name, args } => match name.as_str() {
            "Text" | "Uuid" | "Date" | "DateTime" | "Decimal" | "Email" => "string".to_string(),
            "Int" | "Float" => "number".to_string(),
            "Bool" => "boolean".to_string(),
            "Unit" => "void".to_string(),
            "Json" => "JsonValue".to_string(),
            "Document" => "Document".to_string(),
            "Pdf" => "Pdf".to_string(),
            "Docx" => "Docx".to_string(),
            "SpreadsheetSheet" => "SpreadsheetSheet".to_string(),
            "Spreadsheet" => "Spreadsheet".to_string(),
            "Image" => "Image".to_string(),
            "OcrResult" => "OcrResult".to_string(),
            "List" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("{inner}[]")
            }
            "Map" => {
                let value = args
                    .get(1)
                    .or_else(|| args.first())
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Record<string, {value}>")
            }
            "Money" => {
                let currency = args
                    .first()
                    .map(currency_arg_to_typescript)
                    .unwrap_or_else(|| "string".to_string());
                format!("Money<{currency}>")
            }
            "Option" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Option<{inner}>")
            }
            "Result" => {
                let ok = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                let err = args
                    .get(1)
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Result<{ok}, {err}>")
            }
            "Uncertain" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Uncertain<{inner}>")
            }
            "Secret" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "string".to_string());
                format!("Secret<{inner}>")
            }
            "Brand" => args
                .first()
                .map(type_expr_to_typescript)
                .unwrap_or_else(|| "unknown".to_string()),
            _ if args.is_empty() => name.clone(),
            _ => {
                let args = args
                    .iter()
                    .map(type_expr_to_typescript)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{name}<{args}>")
            }
        },
    }
}

fn type_expr_to_python(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::StringLiteral(value) => format!("Literal[\"{}\"]", escape_python_string(value)),
        TypeExpr::Named { name, args } => match name.as_str() {
            "Text" | "Uuid" | "Date" | "DateTime" | "Decimal" | "Email" | "Url" | "PhoneNumber" => {
                "str".to_string()
            }
            "Int" => "int".to_string(),
            "Float" => "float".to_string(),
            "Bool" => "bool".to_string(),
            "Unit" => "None".to_string(),
            "Json" => "JsonValue".to_string(),
            "Document" => "Document".to_string(),
            "Pdf" => "Pdf".to_string(),
            "Docx" => "Docx".to_string(),
            "SpreadsheetSheet" => "SpreadsheetSheet".to_string(),
            "Spreadsheet" => "Spreadsheet".to_string(),
            "Image" => "Image".to_string(),
            "OcrResult" => "OcrResult".to_string(),
            "List" => {
                let inner = args
                    .first()
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "Any".to_string());
                format!("list[{inner}]")
            }
            "Map" => {
                let value = args
                    .get(1)
                    .or_else(|| args.first())
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "Any".to_string());
                format!("dict[str, {value}]")
            }
            "Money" => "Money[Any]".to_string(),
            "Option" => {
                let inner = args
                    .first()
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "Any".to_string());
                format!("{inner} | None")
            }
            "Result" => {
                let ok = args
                    .first()
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "Any".to_string());
                let err = args
                    .get(1)
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "Any".to_string());
                format!("Ok[{ok}] | Err[{err}]")
            }
            "Uncertain" => {
                let inner = args
                    .first()
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "Any".to_string());
                format!("Uncertain[{inner}]")
            }
            "Secret" => {
                let inner = args
                    .first()
                    .map(type_expr_to_python)
                    .unwrap_or_else(|| "str".to_string());
                format!("Secret[{inner}]")
            }
            "Brand" => args
                .first()
                .map(type_expr_to_python)
                .unwrap_or_else(|| "Any".to_string()),
            _ if args.is_empty() && is_valid_python_identifier(name) => name.clone(),
            _ if args.is_empty() => "Any".to_string(),
            _ if is_valid_python_identifier(name) => {
                let args = args
                    .iter()
                    .map(type_expr_to_python)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{name}[{args}]")
            }
            _ => "Any".to_string(),
        },
    }
}

fn type_expr_to_java(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::StringLiteral(_) => "String".to_string(),
        TypeExpr::Named { name, args } => match name.as_str() {
            "Text" | "Uuid" | "Date" | "DateTime" | "Decimal" | "Email" | "Url" | "PhoneNumber" => {
                "String".to_string()
            }
            "Int" => "long".to_string(),
            "Float" => "double".to_string(),
            "Bool" => "boolean".to_string(),
            "Unit" => "void".to_string(),
            "Json" => "Object".to_string(),
            "Money" => "Money".to_string(),
            "Document" => "Document".to_string(),
            "Pdf" => "Pdf".to_string(),
            "Docx" => "Docx".to_string(),
            "SpreadsheetSheet" => "SpreadsheetSheet".to_string(),
            "Spreadsheet" => "Spreadsheet".to_string(),
            "Image" => "Image".to_string(),
            "OcrResult" => "OcrResult".to_string(),
            "List" => {
                let inner = args
                    .first()
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "Object".to_string());
                format!("List<{inner}>")
            }
            "Map" => {
                let value = args
                    .get(1)
                    .or_else(|| args.first())
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "Object".to_string());
                format!("Map<String, {value}>")
            }
            "Option" => {
                let inner = args
                    .first()
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "Object".to_string());
                format!("Optional<{inner}>")
            }
            "Result" => {
                let ok = args
                    .first()
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "Object".to_string());
                let err = args
                    .get(1)
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "Object".to_string());
                format!("Result<{ok}, {err}>")
            }
            "Uncertain" => {
                let inner = args
                    .first()
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "Object".to_string());
                format!("Uncertain<{inner}>")
            }
            "Secret" => {
                let inner = args
                    .first()
                    .map(type_expr_to_java_boxed)
                    .unwrap_or_else(|| "String".to_string());
                format!("Secret<{inner}>")
            }
            "Brand" => args
                .first()
                .map(type_expr_to_java)
                .unwrap_or_else(|| "Object".to_string()),
            _ if args.is_empty() => java_type_name(name),
            _ => {
                let args = args
                    .iter()
                    .map(type_expr_to_java_boxed)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}<{args}>", java_type_name(name))
            }
        },
    }
}

fn type_expr_to_java_boxed(expr: &TypeExpr) -> String {
    match type_expr_to_java(expr).as_str() {
        "boolean" => "Boolean".to_string(),
        "long" => "Long".to_string(),
        "double" => "Double".to_string(),
        "void" => "Void".to_string(),
        other => other.to_string(),
    }
}

fn currency_arg_to_typescript(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::Named { name, args }
            if args.is_empty()
                && builtins::symbol(name)
                    .is_some_and(|symbol| symbol.kind == BuiltinKind::Currency) =>
        {
            format!("\"{}\"", escape_ts_string(name))
        }
        _ => type_expr_to_typescript(expr),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum TypeExpr {
    Named { name: String, args: Vec<TypeExpr> },
    StringLiteral(String),
}

impl TypeExpr {
    fn render(&self) -> String {
        match self {
            TypeExpr::StringLiteral(value) => format!("\"{}\"", value),
            TypeExpr::Named { name, args } if args.is_empty() => name.clone(),
            TypeExpr::Named { name, args } => {
                let args = args
                    .iter()
                    .map(TypeExpr::render)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{name}<{args}>")
            }
        }
    }
}

fn parse_type_expr(raw: &str) -> TypeExpr {
    let raw = raw.trim();
    if let Some(value) = raw
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
    {
        return TypeExpr::StringLiteral(value.to_string());
    }
    let Some((name, rest)) = raw.split_once('<') else {
        return TypeExpr::Named {
            name: raw.to_string(),
            args: Vec::new(),
        };
    };
    let inner = rest.strip_suffix('>').unwrap_or(rest);
    TypeExpr::Named {
        name: name.trim().to_string(),
        args: split_generic_args(inner)
            .into_iter()
            .map(|arg| parse_type_expr(&arg))
            .collect(),
    }
}

fn split_generic_args(raw: &str) -> Vec<String> {
    let mut args = Vec::new();
    let mut current = String::new();
    let mut depth = 0usize;
    let mut in_string = false;
    let mut prev_escape = false;

    for ch in raw.chars() {
        if in_string {
            current.push(ch);
            if ch == '"' && !prev_escape {
                in_string = false;
            }
            prev_escape = ch == '\\' && !prev_escape;
            continue;
        }

        match ch {
            '"' => {
                in_string = true;
                current.push(ch);
            }
            '<' => {
                depth += 1;
                current.push(ch);
            }
            '>' => {
                depth = depth.saturating_sub(1);
                current.push(ch);
            }
            ',' if depth == 0 => {
                let arg = current.trim();
                if !arg.is_empty() {
                    args.push(arg.to_string());
                }
                current.clear();
            }
            _ => current.push(ch),
        }
        if ch != '\\' {
            prev_escape = false;
        }
    }

    let arg = current.trim();
    if !arg.is_empty() {
        args.push(arg.to_string());
    }
    args
}

fn ts_property_name(name: &str) -> String {
    if is_valid_ts_identifier(name) && !is_ts_reserved_word(name) {
        name.to_string()
    } else {
        format!("\"{}\"", escape_ts_string(name))
    }
}

fn is_valid_ts_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first == '$' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn is_ts_reserved_word(name: &str) -> bool {
    matches!(
        name,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "export"
            | "extends"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
    )
}

fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn python_identifier(name: &str) -> String {
    if is_valid_python_identifier(name) && !is_python_reserved_word(name) {
        name.to_string()
    } else {
        format!("field_{}", sanitize_python_identifier(name))
    }
}

fn python_connector_protocol_name(name: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        out.insert_str(0, "Connector");
    }
    out.push_str("Connector");
    out
}

fn java_connector_interface_name(name: &str) -> String {
    let mut out = java_type_name(name);
    out.push_str("Connector");
    out
}

fn java_type_name(name: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = true;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        out.insert_str(0, "Num");
    }
    if is_java_reserved_word(&out) {
        out.push_str("Value");
    }
    out
}

fn java_identifier(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if (index == 0 && (ch == '_' || ch.is_ascii_alphabetic()))
            || (index > 0 && (ch == '_' || ch.is_ascii_alphanumeric()))
        {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if is_java_reserved_word(&out) {
        out.push('_');
    }
    out
}

fn java_enum_constant(name: &str) -> String {
    let candidate = java_identifier(name);
    if candidate == "_" {
        "VALUE".to_string()
    } else {
        candidate
    }
}

fn render_java_generic_params(out: &mut String, params: &[String]) {
    if params.is_empty() {
        return;
    }
    out.push('<');
    out.push_str(
        &params
            .iter()
            .map(|param| java_type_name(param))
            .collect::<Vec<_>>()
            .join(", "),
    );
    out.push('>');
}

fn is_java_reserved_word(name: &str) -> bool {
    matches!(
        name,
        "abstract"
            | "assert"
            | "boolean"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extends"
            | "final"
            | "finally"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "implements"
            | "import"
            | "instanceof"
            | "int"
            | "interface"
            | "long"
            | "native"
            | "new"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "return"
            | "short"
            | "static"
            | "strictfp"
            | "super"
            | "switch"
            | "synchronized"
            | "this"
            | "throw"
            | "throws"
            | "transient"
            | "try"
            | "void"
            | "volatile"
            | "while"
            | "true"
            | "false"
            | "null"
            | "_"
    )
}

fn sanitize_python_identifier(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if (index == 0 && (ch == '_' || ch.is_ascii_alphabetic()))
            || (index > 0 && (ch == '_' || ch.is_ascii_alphanumeric()))
        {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn is_valid_python_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn is_python_reserved_word(name: &str) -> bool {
    matches!(
        name,
        "False"
            | "None"
            | "True"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "break"
            | "class"
            | "continue"
            | "def"
            | "del"
            | "elif"
            | "else"
            | "except"
            | "finally"
            | "for"
            | "from"
            | "global"
            | "if"
            | "import"
            | "in"
            | "is"
            | "lambda"
            | "nonlocal"
            | "not"
            | "or"
            | "pass"
            | "raise"
            | "return"
            | "try"
            | "while"
            | "with"
            | "yield"
    )
}

fn escape_python_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::{
        parse_type_expr, render_java_sdk, render_python_sdk, render_typescript_sdk,
        split_generic_args, type_ref_to_java, type_ref_to_python, type_ref_to_typescript,
    };
    use num_compiler::{ast::TypeRef, compile};

    #[test]
    fn renders_typescript_connector_sdk() {
        let source = r#"
module sdk.example

type PaymentId = Brand<Text, "PaymentId">

type RefundRequest {
    payment_id: PaymentId
    amount: Money<"KZT">
}

enum Risk {
    Low
    Medium
    High
}

connector payments {
    find(paymentId: PaymentId) -> Option<RefundRequest>
}

connector ai {
    assess(request: RefundRequest) -> Uncertain<Risk>
}

connector documents {
    store(document: Document) -> Document
    inspectPdf(document: Pdf) -> Pdf
    inspectDocx(document: Docx) -> Docx
    inspectSpreadsheet(document: Spreadsheet) -> Spreadsheet
    inspectImage(document: Image) -> Image
    runOcr(image: Image) -> OcrResult
}
"#;
        let compilation = compile("sdk.num", source);
        assert!(compilation.diagnostics.is_empty());

        let sdk = render_typescript_sdk(&compilation.module);

        assert_eq!(sdk.connector_count, 3);
        assert_eq!(sdk.method_count, 8);
        assert!(sdk
            .contents
            .contains("export interface NumConnectorEgressContext"));
        assert!(sdk.contents.contains("export interface Money"));
        assert!(sdk.contents.contains("export type Option<T> = T | null;"));
        assert!(sdk.contents.contains("export interface Uncertain<T>"));
        assert!(sdk.contents.contains("export interface Document"));
        assert!(sdk.contents.contains("size_bytes: number;"));
        assert!(sdk
            .contents
            .contains("export interface Pdf extends Document"));
        assert!(sdk.contents.contains("page_count: number;"));
        assert!(sdk
            .contents
            .contains("export interface Docx extends Document"));
        assert!(sdk.contents.contains("paragraph_count: number;"));
        assert!(sdk.contents.contains("export interface SpreadsheetSheet"));
        assert!(sdk
            .contents
            .contains("export interface Spreadsheet extends Document"));
        assert!(sdk.contents.contains("sheets: SpreadsheetSheet[];"));
        assert!(sdk
            .contents
            .contains("export interface Image extends Document"));
        assert!(sdk.contents.contains("export interface OcrResult"));
        assert!(sdk.contents.contains("confidence: number;"));
        assert!(sdk.contents.contains("export type PaymentId = string;"));
        assert!(sdk.contents.contains("export interface RefundRequest"));
        assert!(sdk
            .contents
            .contains("export type Risk = \"Low\" | \"Medium\" | \"High\";"));
        assert!(sdk
            .contents
            .contains("find(paymentId: PaymentId, context?: NumConnectorEgressContext): Promise<Option<RefundRequest>>;"));
        assert!(sdk
            .contents
            .contains("assess(request: RefundRequest, context?: NumConnectorEgressContext): Promise<Uncertain<Risk>>;"));
        assert!(sdk.contents.contains(
            "store(document: Document, context?: NumConnectorEgressContext): Promise<Document>;"
        ));
        assert!(sdk.contents.contains(
            "inspectPdf(document: Pdf, context?: NumConnectorEgressContext): Promise<Pdf>;"
        ));
        assert!(sdk.contents.contains(
            "inspectDocx(document: Docx, context?: NumConnectorEgressContext): Promise<Docx>;"
        ));
        assert!(sdk.contents.contains(
            "inspectSpreadsheet(document: Spreadsheet, context?: NumConnectorEgressContext): Promise<Spreadsheet>;"
        ));
        assert!(sdk.contents.contains(
            "inspectImage(document: Image, context?: NumConnectorEgressContext): Promise<Image>;"
        ));
        assert!(sdk.contents.contains(
            "runOcr(image: Image, context?: NumConnectorEgressContext): Promise<OcrResult>;"
        ));
    }

    #[test]
    fn maps_nested_generic_type_refs() {
        assert_eq!(
            type_ref_to_typescript(&TypeRef {
                raw: "Result<Option<Money<\"KZT\">>, Text>".to_string()
            }),
            "Result<Option<Money<\"KZT\">>, string>"
        );
        assert_eq!(
            type_ref_to_typescript(&TypeRef {
                raw: "Money<KZT>".to_string()
            }),
            "Money<\"KZT\">"
        );
        assert_eq!(
            type_ref_to_typescript(&TypeRef {
                raw: "Email".to_string()
            }),
            "string"
        );
    }

    #[test]
    fn renders_python_connector_sdk() {
        let source = r#"
module sdk.example

type PaymentId = Brand<Text, "PaymentId">

type RefundRequest {
    payment_id: PaymentId
    amount: Money<"KZT">
}

enum Risk {
    Low
    Medium
    High
}

connector payments {
    find(paymentId: PaymentId) -> Option<RefundRequest>
}

connector ai {
    assess(request: RefundRequest) -> Uncertain<Risk>
}

connector documents {
    store(document: Document) -> Document
    inspect_pdf(document: Pdf) -> Pdf
    inspect_docx(document: Docx) -> Docx
    inspect_spreadsheet(document: Spreadsheet) -> Spreadsheet
    inspect_image(document: Image) -> Image
    run_ocr(image: Image) -> OcrResult
}
"#;
        let compilation = compile("sdk.num", source);
        assert!(compilation.diagnostics.is_empty());

        let sdk = render_python_sdk(&compilation.module);

        assert_eq!(sdk.connector_count, 3);
        assert_eq!(sdk.method_count, 8);
        assert!(sdk.contents.contains("class NumConnectorEgressContext"));
        assert!(sdk
            .contents
            .contains("def num_connector_egress_context_from_json"));
        assert!(sdk.contents.contains("@dataclass(frozen=True)"));
        assert!(sdk.contents.contains("class Money(Generic[T]):"));
        assert!(sdk.contents.contains("class Uncertain(Generic[T]):"));
        assert!(sdk.contents.contains("class Document:"));
        assert!(sdk.contents.contains("    size_bytes: int"));
        assert!(sdk.contents.contains("class Pdf(Document):"));
        assert!(sdk.contents.contains("    page_count: int"));
        assert!(sdk.contents.contains("class Docx(Document):"));
        assert!(sdk.contents.contains("    paragraph_count: int"));
        assert!(sdk.contents.contains("class SpreadsheetSheet:"));
        assert!(sdk.contents.contains("class Spreadsheet(Document):"));
        assert!(sdk.contents.contains("    sheets: list[SpreadsheetSheet]"));
        assert!(sdk.contents.contains("class Image(Document):"));
        assert!(sdk.contents.contains("class OcrResult:"));
        assert!(sdk.contents.contains("    confidence: float"));
        assert!(sdk.contents.contains("PaymentId: TypeAlias = str"));
        assert!(sdk.contents.contains("class RefundRequest:"));
        assert!(sdk.contents.contains(
            "Risk: TypeAlias = Literal[\"Low\"] | Literal[\"Medium\"] | Literal[\"High\"]"
        ));
        assert!(sdk.contents.contains("class PaymentsConnector(Protocol):"));
        assert!(sdk.contents.contains("def find(self, paymentId: PaymentId, context: NumConnectorEgressContext | None = None) -> RefundRequest | None: ..."));
        assert!(sdk.contents.contains("def assess(self, request: RefundRequest, context: NumConnectorEgressContext | None = None) -> Uncertain[Risk]: ..."));
        assert!(sdk.contents.contains("def store(self, document: Document, context: NumConnectorEgressContext | None = None) -> Document: ..."));
        assert!(sdk.contents.contains("def inspect_pdf(self, document: Pdf, context: NumConnectorEgressContext | None = None) -> Pdf: ..."));
        assert!(sdk.contents.contains("def inspect_docx(self, document: Docx, context: NumConnectorEgressContext | None = None) -> Docx: ..."));
        assert!(sdk.contents.contains("def inspect_spreadsheet(self, document: Spreadsheet, context: NumConnectorEgressContext | None = None) -> Spreadsheet: ..."));
        assert!(sdk.contents.contains("def inspect_image(self, document: Image, context: NumConnectorEgressContext | None = None) -> Image: ..."));
        assert!(sdk.contents.contains("def run_ocr(self, image: Image, context: NumConnectorEgressContext | None = None) -> OcrResult: ..."));
    }

    #[test]
    fn renders_java_connector_sdk() {
        let source = r#"
module sdk.jvm

type PaymentId = Brand<Text, "PaymentId">

type RefundRequest {
    payment_id: PaymentId
    amount: Money<"KZT">
    metadata: Json
}

enum Risk {
    Low
    High
}

enum Decision {
    Approved(RefundRequest)
    Rejected(Text)
}

fn normalize(raw: Text) -> Text {
    return raw
}

connector payments {
    find(paymentId: PaymentId) -> Option<RefundRequest>
    submit(request: RefundRequest) -> Result<Decision, Text>
}
"#;
        let compilation = compile("sdk.num", source);
        assert!(
            compilation.diagnostics.is_empty(),
            "Diagnostics: {:?}",
            compilation.diagnostics
        );

        let sdk = render_java_sdk(&compilation.module);

        assert_eq!(sdk.connector_count, 1);
        assert_eq!(sdk.method_count, 3);
        assert_eq!(sdk.language, super::ConnectorSdkLanguage::Java);
        assert!(sdk.contents.contains("public final class NumConnectorSdk"));
        assert!(sdk.contents.contains("public record NumConnectorContext"));
        assert!(sdk
            .contents
            .contains("public static class NumConnectorException extends Exception"));
        assert!(sdk.contents.contains("public record Money"));
        assert!(sdk
            .contents
            .contains("public sealed interface Result<T, E>"));
        assert!(sdk
            .contents
            .contains("public record PaymentId(String value)"));
        assert!(sdk.contents.contains(
            "public record RefundRequest(PaymentId payment_id, Money amount, Object metadata)"
        ));
        assert!(sdk.contents.contains("public enum Risk { Low, High }"));
        assert!(sdk.contents.contains(
            "public sealed interface Decision permits Decision.Approved, Decision.Rejected"
        ));
        assert!(sdk.contents.contains(
            "String normalize(String raw, NumConnectorContext context) throws NumConnectorException;"
        ));
        assert!(sdk.contents.contains("public interface PaymentsConnector"));
        assert!(sdk.contents.contains(
            "Optional<RefundRequest> find(PaymentId paymentId, NumConnectorContext context) throws NumConnectorException;"
        ));
        assert!(sdk.contents.contains(
            "Result<Decision, String> submit(RefundRequest request, NumConnectorContext context) throws NumConnectorException;"
        ));
        assert!(sdk.contents.contains("PaymentsConnector payments();"));
    }

    #[test]
    fn maps_nested_generic_type_refs_to_python() {
        assert_eq!(
            type_ref_to_python(&TypeRef {
                raw: "Result<Option<Money<\"KZT\">>, Text>".to_string()
            }),
            "Ok[Money[Any] | None] | Err[str]"
        );
        assert_eq!(
            type_ref_to_python(&TypeRef {
                raw: "List<Email>".to_string()
            }),
            "list[str]"
        );
        assert_eq!(
            type_ref_to_python(&TypeRef {
                raw: "Unmapped-Type".to_string()
            }),
            "Any"
        );
    }

    #[test]
    fn maps_nested_generic_type_refs_to_java() {
        assert_eq!(
            type_ref_to_java(&TypeRef {
                raw: "Result<Option<Money<\"KZT\">>, Text>".to_string()
            }),
            "Result<Optional<Money>, String>"
        );
        assert_eq!(
            type_ref_to_java(&TypeRef {
                raw: "List<Int>".to_string()
            }),
            "List<Long>"
        );
        assert_eq!(
            type_ref_to_java(&TypeRef {
                raw: "Json".to_string()
            }),
            "Object"
        );
    }

    #[test]
    fn splits_nested_generic_args() {
        assert_eq!(
            split_generic_args("Option<Money<\"KZT\">>, Result<Text, Json>"),
            vec!["Option<Money<\"KZT\">>", "Result<Text, Json>"]
        );
        assert_eq!(parse_type_expr("Text").render(), "Text");
    }
}
