use num_compiler::{
    ast::{ConnectorDecl, Declaration, EnumDecl, Module, TypeBody, TypeDecl, TypeRef},
    builtins::{self, BuiltinKind},
};
use serde_json::{json, Value};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConnectorSdkLanguage {
    TypeScript,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConnectorSdk {
    pub language: ConnectorSdkLanguage,
    pub connector_count: usize,
    pub method_count: usize,
    pub type_count: usize,
    pub contents: String,
}

impl ConnectorSdk {
    pub fn to_json(&self) -> Value {
        json!({
            "language": match self.language {
                ConnectorSdkLanguage::TypeScript => "typescript",
            },
            "connector_count": self.connector_count,
            "method_count": self.method_count,
            "type_count": self.type_count,
        })
    }
}

pub fn render_typescript_sdk(module: &Module) -> ConnectorSdk {
    let type_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Type(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let enum_decls = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Enum(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();
    let connectors = module
        .declarations
        .iter()
        .filter_map(|decl| match decl {
            Declaration::Connector(decl) => Some(decl),
            _ => None,
        })
        .collect::<Vec<_>>();

    let mut wrappers = WrapperUsage::default();
    for decl in &type_decls {
        collect_type_wrappers(decl, &mut wrappers);
    }
    for decl in &enum_decls {
        collect_enum_wrappers(decl, &mut wrappers);
    }
    for connector in &connectors {
        collect_connector_wrappers(connector, &mut wrappers);
    }

    let mut out = String::new();
    out.push_str("/* Generated by num connector-sdk. Do not edit by hand. */\n\n");
    render_runtime_wrappers(&mut out, &wrappers);
    render_type_declarations(&mut out, &type_decls);
    render_enum_declarations(&mut out, &enum_decls);
    render_connector_interface(&mut out, &connectors);

    ConnectorSdk {
        language: ConnectorSdkLanguage::TypeScript,
        connector_count: connectors.len(),
        method_count: connectors
            .iter()
            .map(|connector| connector.methods.len())
            .sum(),
        type_count: type_decls.len() + enum_decls.len(),
        contents: out,
    }
}

#[derive(Debug, Default)]
struct WrapperUsage {
    money: bool,
    option: bool,
    result: bool,
    uncertain: bool,
    secret: bool,
    json: bool,
}

fn render_runtime_wrappers(out: &mut String, wrappers: &WrapperUsage) {
    if wrappers.json {
        out.push_str("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n");
    }
    if wrappers.money {
        out.push_str("export interface Money<C extends string = string> {\n");
        out.push_str("  currency: C;\n");
        out.push_str("  cents: number;\n");
        out.push_str("}\n\n");
    }
    if wrappers.option {
        out.push_str("export type Option<T> = T | null;\n\n");
    }
    if wrappers.result {
        out.push_str(
            "export type Result<T, E> = { ok: true; value: T } | { ok: false; error: E };\n\n",
        );
    }
    if wrappers.uncertain {
        out.push_str("export interface Uncertain<T> {\n");
        out.push_str("  value: T;\n");
        out.push_str("  confidence: number;\n");
        out.push_str("  source?: string;\n");
        out.push_str("  explanation?: string;\n");
        out.push_str("  evidence?: string[];\n");
        out.push_str("}\n\n");
    }
    if wrappers.secret {
        out.push_str("export interface Secret<T = string> {\n");
        out.push_str("  name: string;\n");
        out.push_str("  value?: T;\n");
        out.push_str("}\n\n");
    }
}

fn render_type_declarations(out: &mut String, declarations: &[&TypeDecl]) {
    for decl in declarations {
        match &decl.body {
            TypeBody::Struct(fields) => {
                out.push_str("export interface ");
                out.push_str(&decl.name);
                render_generic_params(out, &decl.generic_params);
                out.push_str(" {\n");
                for field in fields {
                    out.push_str("  ");
                    out.push_str(&ts_property_name(&field.name));
                    out.push_str(": ");
                    out.push_str(&type_ref_to_typescript(&field.ty));
                    out.push_str(";\n");
                }
                out.push_str("}\n\n");
            }
            TypeBody::Alias(alias) => {
                out.push_str("export type ");
                out.push_str(&decl.name);
                render_generic_params(out, &decl.generic_params);
                out.push_str(" = ");
                out.push_str(&type_ref_to_typescript(alias));
                out.push_str(";\n\n");
            }
        }
    }
}

fn render_enum_declarations(out: &mut String, declarations: &[&EnumDecl]) {
    for decl in declarations {
        let has_payload = decl
            .variants
            .iter()
            .any(|variant| variant.payload.is_some());
        out.push_str("export type ");
        out.push_str(&decl.name);
        out.push_str(" = ");
        if has_payload {
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str("\n  | ");
                }
                out.push_str("{ kind: \"");
                out.push_str(&variant.name);
                out.push('"');
                if let Some(payload) = &variant.payload {
                    out.push_str("; value: ");
                    out.push_str(&type_ref_to_typescript(payload));
                }
                out.push_str(" }");
            }
            out.push_str(";\n\n");
        } else {
            for (index, variant) in decl.variants.iter().enumerate() {
                if index > 0 {
                    out.push_str(" | ");
                }
                out.push('"');
                out.push_str(&variant.name);
                out.push('"');
            }
            out.push_str(";\n\n");
        }
    }
}

fn render_connector_interface(out: &mut String, connectors: &[&ConnectorDecl]) {
    out.push_str("export interface NumConnectors {\n");
    for connector in connectors {
        out.push_str("  ");
        out.push_str(&ts_property_name(&connector.name));
        out.push_str(": {\n");
        for method in &connector.methods {
            out.push_str("    ");
            out.push_str(&ts_property_name(&method.name));
            out.push('(');
            for (index, param) in method.params.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }
                out.push_str(&ts_property_name(&param.name));
                out.push_str(": ");
                out.push_str(&type_ref_to_typescript(&param.ty));
            }
            out.push_str("): Promise<");
            out.push_str(
                &method
                    .result
                    .as_ref()
                    .map(type_ref_to_typescript)
                    .unwrap_or_else(|| "void".to_string()),
            );
            out.push_str(">;\n");
        }
        out.push_str("  };\n");
    }
    out.push_str("}\n");
}

fn render_generic_params(out: &mut String, params: &[String]) {
    if params.is_empty() {
        return;
    }
    out.push('<');
    out.push_str(&params.join(", "));
    out.push('>');
}

fn collect_type_wrappers(decl: &TypeDecl, wrappers: &mut WrapperUsage) {
    match &decl.body {
        TypeBody::Struct(fields) => {
            for field in fields {
                collect_wrappers_from_type(&field.ty, wrappers);
            }
        }
        TypeBody::Alias(alias) => collect_wrappers_from_type(alias, wrappers),
    }
}

fn collect_enum_wrappers(decl: &EnumDecl, wrappers: &mut WrapperUsage) {
    for variant in &decl.variants {
        if let Some(payload) = &variant.payload {
            collect_wrappers_from_type(payload, wrappers);
        }
    }
}

fn collect_connector_wrappers(connector: &ConnectorDecl, wrappers: &mut WrapperUsage) {
    for method in &connector.methods {
        for param in &method.params {
            collect_wrappers_from_type(&param.ty, wrappers);
        }
        if let Some(result) = &method.result {
            collect_wrappers_from_type(result, wrappers);
        }
    }
}

fn collect_wrappers_from_type(ty: &TypeRef, wrappers: &mut WrapperUsage) {
    match parse_type_expr(&ty.raw) {
        TypeExpr::Named { name, args } => {
            match name.as_str() {
                "Money" => wrappers.money = true,
                "Option" => wrappers.option = true,
                "Result" => wrappers.result = true,
                "Uncertain" => wrappers.uncertain = true,
                "Secret" => wrappers.secret = true,
                "Json" => wrappers.json = true,
                _ => {}
            }
            for arg in args {
                collect_wrappers_from_type(&TypeRef { raw: arg.render() }, wrappers);
            }
        }
        TypeExpr::StringLiteral(_) => {}
    }
}

fn type_ref_to_typescript(ty: &TypeRef) -> String {
    type_expr_to_typescript(&parse_type_expr(&ty.raw))
}

fn type_expr_to_typescript(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::StringLiteral(value) => format!("\"{}\"", escape_ts_string(value)),
        TypeExpr::Named { name, args } => match name.as_str() {
            "Text" | "Uuid" | "Date" | "DateTime" | "Decimal" | "Email" => "string".to_string(),
            "Int" | "Float" => "number".to_string(),
            "Bool" => "boolean".to_string(),
            "Unit" => "void".to_string(),
            "Json" => "JsonValue".to_string(),
            "List" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("{inner}[]")
            }
            "Map" => {
                let value = args
                    .get(1)
                    .or_else(|| args.first())
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Record<string, {value}>")
            }
            "Money" => {
                let currency = args
                    .first()
                    .map(currency_arg_to_typescript)
                    .unwrap_or_else(|| "string".to_string());
                format!("Money<{currency}>")
            }
            "Option" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Option<{inner}>")
            }
            "Result" => {
                let ok = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                let err = args
                    .get(1)
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Result<{ok}, {err}>")
            }
            "Uncertain" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "unknown".to_string());
                format!("Uncertain<{inner}>")
            }
            "Secret" => {
                let inner = args
                    .first()
                    .map(type_expr_to_typescript)
                    .unwrap_or_else(|| "string".to_string());
                format!("Secret<{inner}>")
            }
            "Brand" => args
                .first()
                .map(type_expr_to_typescript)
                .unwrap_or_else(|| "unknown".to_string()),
            _ if args.is_empty() => name.clone(),
            _ => {
                let args = args
                    .iter()
                    .map(type_expr_to_typescript)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{name}<{args}>")
            }
        },
    }
}

fn currency_arg_to_typescript(expr: &TypeExpr) -> String {
    match expr {
        TypeExpr::Named { name, args }
            if args.is_empty()
                && builtins::symbol(name)
                    .is_some_and(|symbol| symbol.kind == BuiltinKind::Currency) =>
        {
            format!("\"{}\"", escape_ts_string(name))
        }
        _ => type_expr_to_typescript(expr),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum TypeExpr {
    Named { name: String, args: Vec<TypeExpr> },
    StringLiteral(String),
}

impl TypeExpr {
    fn render(&self) -> String {
        match self {
            TypeExpr::StringLiteral(value) => format!("\"{}\"", value),
            TypeExpr::Named { name, args } if args.is_empty() => name.clone(),
            TypeExpr::Named { name, args } => {
                let args = args
                    .iter()
                    .map(TypeExpr::render)
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{name}<{args}>")
            }
        }
    }
}

fn parse_type_expr(raw: &str) -> TypeExpr {
    let raw = raw.trim();
    if let Some(value) = raw
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
    {
        return TypeExpr::StringLiteral(value.to_string());
    }
    let Some((name, rest)) = raw.split_once('<') else {
        return TypeExpr::Named {
            name: raw.to_string(),
            args: Vec::new(),
        };
    };
    let inner = rest.strip_suffix('>').unwrap_or(rest);
    TypeExpr::Named {
        name: name.trim().to_string(),
        args: split_generic_args(inner)
            .into_iter()
            .map(|arg| parse_type_expr(&arg))
            .collect(),
    }
}

fn split_generic_args(raw: &str) -> Vec<String> {
    let mut args = Vec::new();
    let mut current = String::new();
    let mut depth = 0usize;
    let mut in_string = false;
    let mut prev_escape = false;

    for ch in raw.chars() {
        if in_string {
            current.push(ch);
            if ch == '"' && !prev_escape {
                in_string = false;
            }
            prev_escape = ch == '\\' && !prev_escape;
            continue;
        }

        match ch {
            '"' => {
                in_string = true;
                current.push(ch);
            }
            '<' => {
                depth += 1;
                current.push(ch);
            }
            '>' => {
                depth = depth.saturating_sub(1);
                current.push(ch);
            }
            ',' if depth == 0 => {
                let arg = current.trim();
                if !arg.is_empty() {
                    args.push(arg.to_string());
                }
                current.clear();
            }
            _ => current.push(ch),
        }
        if ch != '\\' {
            prev_escape = false;
        }
    }

    let arg = current.trim();
    if !arg.is_empty() {
        args.push(arg.to_string());
    }
    args
}

fn ts_property_name(name: &str) -> String {
    if is_valid_ts_identifier(name) && !is_ts_reserved_word(name) {
        name.to_string()
    } else {
        format!("\"{}\"", escape_ts_string(name))
    }
}

fn is_valid_ts_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first == '_' || first == '$' || first.is_ascii_alphabetic()) {
        return false;
    }
    chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn is_ts_reserved_word(name: &str) -> bool {
    matches!(
        name,
        "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "export"
            | "extends"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "import"
            | "in"
            | "instanceof"
            | "new"
            | "return"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
    )
}

fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::{
        parse_type_expr, render_typescript_sdk, split_generic_args, type_ref_to_typescript,
    };
    use num_compiler::{ast::TypeRef, compile};

    #[test]
    fn renders_typescript_connector_sdk() {
        let source = r#"
module sdk.example

type PaymentId = Brand<Text, "PaymentId">

type RefundRequest {
    payment_id: PaymentId
    amount: Money<"KZT">
}

enum Risk {
    Low
    Medium
    High
}

connector payments {
    find(paymentId: PaymentId) -> Option<RefundRequest>
}

connector ai {
    assess(request: RefundRequest) -> Uncertain<Risk>
}
"#;
        let compilation = compile("sdk.num", source);
        assert!(compilation.diagnostics.is_empty());

        let sdk = render_typescript_sdk(&compilation.module);

        assert_eq!(sdk.connector_count, 2);
        assert_eq!(sdk.method_count, 2);
        assert!(sdk.contents.contains("export interface Money"));
        assert!(sdk.contents.contains("export type Option<T> = T | null;"));
        assert!(sdk.contents.contains("export interface Uncertain<T>"));
        assert!(sdk.contents.contains("export type PaymentId = string;"));
        assert!(sdk.contents.contains("export interface RefundRequest"));
        assert!(sdk
            .contents
            .contains("export type Risk = \"Low\" | \"Medium\" | \"High\";"));
        assert!(sdk
            .contents
            .contains("find(paymentId: PaymentId): Promise<Option<RefundRequest>>;"));
        assert!(sdk
            .contents
            .contains("assess(request: RefundRequest): Promise<Uncertain<Risk>>;"));
    }

    #[test]
    fn maps_nested_generic_type_refs() {
        assert_eq!(
            type_ref_to_typescript(&TypeRef {
                raw: "Result<Option<Money<\"KZT\">>, Text>".to_string()
            }),
            "Result<Option<Money<\"KZT\">>, string>"
        );
        assert_eq!(
            type_ref_to_typescript(&TypeRef {
                raw: "Money<KZT>".to_string()
            }),
            "Money<\"KZT\">"
        );
        assert_eq!(
            type_ref_to_typescript(&TypeRef {
                raw: "Email".to_string()
            }),
            "string"
        );
    }

    #[test]
    fn splits_nested_generic_args() {
        assert_eq!(
            split_generic_args("Option<Money<\"KZT\">>, Result<Text, Json>"),
            vec!["Option<Money<\"KZT\">>", "Result<Text, Json>"]
        );
        assert_eq!(parse_type_expr("Text").render(), "Text");
    }
}
